export const API_ENDPOINTS = {
  LOGIN: "/login",
  REGISTER: "/register",
  UPDATE: "/update",
  LOGOUT: "/logout",
  CHANGEPASS: "/update-password",
  FORGET_PASSWORD: "/forget-password",
  CATEGORIES: "/categories.json",
  FEATURED_CATEGORIES: "/featured_categories.json",
  COLLECTIONS: "/collections.json",
  BRANDS: "/brands.json",
  PRODUCTS: "https://api.tagplus.com.br/produtos",
  FEATURED_PRODUCTS: "/featured_products.json",
  TOP_SELLER_PRODUCTS: "/products_top_seller.json",
  ON_SELLING_PRODUCTS: "/products_on_selling.json",
  PRODUCT: "/product.json",
  RELATED_PRODUCTS: "/related_products.json",
  BEST_SELLER_PRODUCTS: "/products_best_seller.json",
  NEW_ARRIVAL_PRODUCTS: "/products_new_arrival.json",
  FLASH_SALE_PRODUCTS: "/products_flash_sale.json",
  SEARCH: "/search.json",
  ORDERS: "/orders.json",
  ORDER: "/order.json",
};
